
import React, { useState, useEffect } from 'react';
import { Order, SystemConfig, DEFAULT_CONFIG } from './types';
import { OrderForm } from './components/OrderForm';
import { OrderList } from './components/OrderList';
import { AdminPanel } from './components/AdminPanel';
import { AdminLogin } from './components/AdminLogin';
import { AppLogin } from './components/AppLogin';
import { Dashboard } from './components/Dashboard';
import { Button } from './components/ui/Button';
import { Plus, LayoutGrid, List, RefreshCw, Loader2, AlertTriangle, Globe, Lock, Database, Download, BarChart3 } from 'lucide-react';
import { fetchOrders, createOrder, updateOrder, deleteOrder, fetchConfig, saveConfig } from './lib/appwrite';

function App() {
  const [view, setView] = useState<'list' | 'form' | 'admin' | 'dashboard'>('list');
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [missingAttribute, setMissingAttribute] = useState<string>('');
  
  const [orders, setOrders] = useState<Order[]>([]);
  const [config, setConfig] = useState<SystemConfig>(DEFAULT_CONFIG);
  const [configDocId, setConfigDocId] = useState<string>('');

  const [editingOrder, setEditingOrder] = useState<Order | null>(null);

  // Auth State
  const [isAppAuthenticated, setIsAppAuthenticated] = useState(false);
  const [isAdminAuthenticated, setIsAdminAuthenticated] = useState(false);

  // Initial Load - Only when authenticated
  useEffect(() => {
    if (isAppAuthenticated) {
        loadData();
    }
  }, [isAppAuthenticated]);

  const loadData = async () => {
    setLoading(true);
    setError(null);
    try {
        const [loadedOrders, loadedConfigData] = await Promise.all([
            fetchOrders(),
            fetchConfig()
        ]);
        
        setOrders(loadedOrders);
        setConfig(loadedConfigData.config);
        setConfigDocId(loadedConfigData.docId);
    } catch (err: any) {
        console.error("Erro ao carregar dados:", err);
        handleError(err);
    } finally {
        setLoading(false);
    }
  };

  // Centralized Error Handler
  const handleError = (err: any) => {
      const msg = (err.message || '').toLowerCase();
      const code = err.code;

      if (msg.includes('failed to fetch') || msg.includes('network request failed')) {
          setError('connection'); // CORS error
      } else if (code === 401 || code === 403 || msg.includes('unauthorized') || msg.includes('not authorized') || msg.includes('permissions')) {
          setError('auth'); // Permission error
      } else if (msg.includes('unknown attribute') || msg.includes('invalid document structure') || msg.includes('missing required attribute')) {
          // Extract attribute name if possible
          // Regex robusto para pegar 'Unknown attribute: "nome"' ou 'Missing required attribute "nome"'
          const match = err.message.match(/(?:Unknown attribute|Missing required attribute)[:\s]+["']?([^"']+)["']?/i);
          
          if (match && match[1]) {
              setMissingAttribute(match[1]);
          } else {
              // Fallback if regex fails but we know it's about structure
              if (msg.includes('atualizadopor')) setMissingAttribute('atualizadoPor');
              else if (msg.includes('value')) setMissingAttribute('value');
              else if (msg.includes('datatype')) setMissingAttribute('datatype');
              else if (msg.includes('isactive')) setMissingAttribute('isActive');
              else if (msg.includes('createdat')) setMissingAttribute('createdAt');
              else if (msg.includes('updatedat')) setMissingAttribute('updatedAt');
              else setMissingAttribute('algum campo faltando');
          }
          setError('schema');
      } else {
          if (loading) {
              setError(err.message || 'Ocorreu um erro desconhecido.');
          } else {
              alert("Erro: " + (err.message || "Falha na operação"));
          }
      }
  };

  const handleSaveOrder = async (orderData: Order) => {
    setLoading(true);
    try {
      if (editingOrder) {
        // Update existing
        await updateOrder(orderData.id, orderData);
      } else {
        // Create new (Remove fake ID generated by form before sending)
        const { id, dataCriacao, ...newOrderPayload } = orderData;
        await createOrder(newOrderPayload);
      }
      await loadData(); // Refresh list
      setView('list');
      setEditingOrder(null);
    } catch (err: any) {
      console.error("Erro ao salvar:", err);
      handleError(err);
    } finally {
      setLoading(false);
    }
  };

  const handleDeleteOrder = async (id: string) => {
    setLoading(true);
    try {
        await deleteOrder(id);
        await loadData();
    } catch (err: any) {
        console.error("Erro ao excluir:", err);
        // Se for erro de permissão, dá um feedback mais direto antes de mudar a tela
        if (err.code === 401 || err.code === 403) {
            alert("ERRO DE PERMISSÃO: Você precisa habilitar a permissão 'DELETE' (Excluir) nas configurações da coleção 'orders' no Appwrite Console.");
        }
        handleError(err);
    } finally {
        setLoading(false);
    }
  };

  const handleExportExcel = () => {
    if (orders.length === 0) {
        alert("Não há registros para exportar.");
        return;
    }

    // Cabeçalhos do CSV
    const headers = [
        "Registro", "Cliente", "Cidade", "Cluster", "Status",
        "Supervisor", "Alt. Rede", "Rede Designada", "Rede Construída",
        "Chamado", "Atualizado Por", "Data Criação", "Obs"
    ];

    // Gera as linhas
    const csvRows = orders.map(order => {
        const dateStr = new Date(order.dataCriacao).toLocaleDateString('pt-BR');
        // Função auxiliar para tratar campos com texto (aspas, ponto e vírgula, quebras de linha)
        const safe = (str: string) => `"${(str || '').replace(/"/g, '""').replace(/\n/g, ' ')}"`;

        return [
            safe(order.pedido),
            safe(order.cliente),
            safe(order.cidade),
            safe(order.cluster),
            safe(order.status),
            safe(order.supervisor),
            safe(order.alteracaoRede),
            safe(order.redeDesignada),
            safe(order.redeConstruida),
            safe(order.chamado),
            safe(order.atualizadoPor),
            safe(dateStr),
            safe(order.obs)
        ].join(';'); // Ponto e vírgula é melhor para Excel no Brasil
    });

    // Adiciona BOM (\uFEFF) para garantir UTF-8 correto no Excel
    const csvString = `\uFEFF${headers.join(';')}\n${csvRows.join('\n')}`;
    
    // Cria o blob e link de download
    const blob = new Blob([csvString], { type: 'text/csv;charset=utf-8;' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `Registros_VIVO_${new Date().toLocaleDateString('pt-BR').replace(/\//g, '-')}.csv`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handleUpdateConfig = async (newConfig: SystemConfig) => {
    setLoading(true);
    try {
        const response = await saveConfig(configDocId, newConfig);
        setConfig(newConfig);
        if (!configDocId && response && response.$id) {
            setConfigDocId(response.$id);
        }
        alert("Configurações salvas com sucesso!");
    } catch (err: any) {
        console.error("Erro ao salvar config:", err);
        handleError(err);
    } finally {
        setLoading(false);
    }
  };

  const handleEditOrder = (order: Order) => {
    setEditingOrder(order);
    setView('form');
  };

  const handleCreateNew = () => {
    setEditingOrder(null);
    setView('form');
  };

  const handleAdminClick = () => {
    setView('admin');
  };

  // --- APP LOGIN CHECK ---
  if (!isAppAuthenticated) {
    return <AppLogin onLoginSuccess={() => setIsAppAuthenticated(true)} />;
  }

  // LOADING SCREEN (Initial only)
  if (loading && orders.length === 0 && !error) {
     return (
        <div className="min-h-screen flex flex-col items-center justify-center bg-lilac-50 text-lilac-600">
            <Loader2 className="w-12 h-12 animate-spin mb-4" />
            <p className="font-bold text-lg">Conectando ao banco de dados...</p>
        </div>
     );
  }

  // ERROR SCREENS (Schema, Auth, Connection)
  if (error === 'schema') {
    return (
        <div className="min-h-screen flex flex-col items-center justify-center bg-lilac-50 p-4 font-sans">
            <div className="bg-white p-8 rounded-3xl shadow-xl max-w-2xl w-full border border-lilac-200 animate-fadeIn">
                <div className="flex items-center gap-3 text-amber-600 mb-6">
                    <Database size={40} />
                    <h1 className="text-2xl font-bold">Campo Faltando no Banco</h1>
                </div>
                <p className="text-slate-600 mb-6 text-lg">O Appwrite recusou os dados porque falta criar um campo na coleção.</p>
                <div className="bg-amber-50 p-6 rounded-2xl border border-amber-100 mb-6">
                    <p className="font-bold text-amber-800">Campo faltando:</p>
                    <p className="text-2xl font-mono text-amber-600 mt-2 bg-white inline-block px-3 py-1 rounded border border-amber-200">{missingAttribute}</p>
                </div>
                <div className="space-y-4 text-slate-700 text-sm bg-lilac-50 p-6 rounded-2xl border border-lilac-100">
                    <p className="font-bold text-lilac-900">Como corrigir:</p>
                    <ol className="list-decimal list-inside space-y-2">
                        <li>Acesse o <strong>Appwrite Console</strong> &gt; <strong>Databases</strong> &gt; <strong>GestorDB</strong>.</li>
                        <li>Clique na coleção <strong>orders</strong> ou <strong>config</strong> (dependendo de onde ocorreu o erro).</li>
                        <li>Clique na aba <strong>Attributes</strong>.</li>
                        <li>Clique em <strong>Create Attribute</strong> &gt; <strong>String</strong>.</li>
                        <li>No campo <strong>Attribute Key</strong>, digite exatamente: <strong>{missingAttribute}</strong></li>
                        <li>Defina o tamanho (Size) como <strong>255</strong>.</li>
                        <li>Clique em <strong>Create</strong>.</li>
                    </ol>
                </div>
                <div className="mt-8 flex justify-center">
                    <Button onClick={() => { setError(null); }} size="lg" icon={<RefreshCw />}>Já criei, tentar novamente</Button>
                </div>
            </div>
        </div>
    );
  }

  if (error === 'auth') {
    return (
        <div className="min-h-screen flex flex-col items-center justify-center bg-lilac-50 p-4 font-sans">
            <div className="bg-white p-8 rounded-3xl shadow-xl max-w-2xl w-full border border-lilac-200 animate-fadeIn">
                <div className="flex items-center gap-3 text-rose-600 mb-6">
                    <Lock size={40} />
                    <h1 className="text-2xl font-bold">Falta Permissão (Especialmente DELETE)</h1>
                </div>
                <p className="text-slate-600 mb-6 text-lg">O Appwrite bloqueou a operação. Isso quase sempre acontece porque a permissão <strong>DELETE (Excluir)</strong> não foi marcada nas configurações.</p>
                <div className="bg-lilac-50 p-6 rounded-2xl border border-lilac-100 space-y-4">
                    <h3 className="font-bold text-lilac-900 flex items-center gap-2"><SettingsIcon size={20} /> Como corrigir no Appwrite Console:</h3>
                    <div className="space-y-4 text-slate-700 text-sm">
                        <p className="font-medium text-rose-600">Execute estes passos para as coleções "orders" e "config":</p>
                        <ol className="list-decimal list-inside space-y-2">
                            <li>Vá em <strong>Databases</strong> &gt; <strong>GestorDB</strong>.</li>
                            <li>Clique na coleção (ex: <strong>orders</strong>).</li>
                            <li>Clique na aba <strong>Settings</strong>.</li>
                            <li>Role até a seção <strong>Permissions</strong>.</li>
                            <li>Clique em <strong>Update</strong> ao lado do papel <strong>Any</strong> (ou adicione se não existir).</li>
                            <li>⚠️ <strong>IMPORTANTE:</strong> Certifique-se que <strong>DELETE</strong> está marcado, além de Read, Create e Update.</li>
                            <li>Clique em <strong>Update</strong> para salvar.</li>
                        </ol>
                    </div>
                </div>
                <div className="mt-8 flex justify-center">
                    <Button onClick={loadData} size="lg" icon={<RefreshCw />}>Já corrigi, tentar novamente</Button>
                </div>
            </div>
        </div>
    );
  }

  if (error === 'connection') {
    return (
        <div className="min-h-screen flex flex-col items-center justify-center bg-lilac-50 p-4 font-sans">
            <div className="bg-white p-8 rounded-3xl shadow-xl max-w-2xl w-full border border-lilac-200 animate-fadeIn">
                <div className="flex items-center gap-3 text-amber-600 mb-6">
                    <AlertTriangle size={40} />
                    <h1 className="text-2xl font-bold">Acesso Bloqueado (Segurança)</h1>
                </div>
                <p className="text-slate-600 mb-6 text-lg">O navegador bloqueou a conexão ("Failed to fetch"). Isso acontece porque o Appwrite exige que você autorize este site/app.</p>
                <div className="bg-lilac-50 p-6 rounded-2xl border border-lilac-100 space-y-4">
                    <h3 className="font-bold text-lilac-900 flex items-center gap-2"><Globe size={20} /> Como liberar o acesso:</h3>
                    <ol className="list-decimal list-inside space-y-3 text-slate-700">
                        <li>Acesse o painel: <a href="https://cloud.appwrite.io" target="_blank" className="text-lilac-600 font-bold underline hover:text-lilac-800">Appwrite Console</a>.</li>
                        <li>Entre no projeto <strong>Gestor VIVO_SC</strong>.</li>
                        <li>Na tela inicial (Overview), role até o final para encontrar <strong>Platforms</strong>.</li>
                        <li>Clique em <span className="bg-white px-2 py-1 rounded border font-bold text-xs">Add Platform</span> e escolha <strong>Web App</strong>.</li>
                        <li>
                            Preencha os campos:
                            <ul className="list-disc list-inside ml-6 mt-1 text-sm text-slate-600">
                                <li>Name: <span className="font-mono bg-white px-1 border rounded">Meu App</span></li>
                                <li>Hostname: <span className="font-mono bg-white px-1 border rounded">*</span> (Coloque apenas um asterisco)</li>
                            </ul>
                        </li>
                        <li>Clique em <strong>Next</strong> para salvar.</li>
                    </ol>
                </div>
                <div className="mt-8 flex justify-center">
                    <Button onClick={loadData} size="lg" icon={<RefreshCw />}>Já fiz isso, tentar novamente</Button>
                </div>
            </div>
        </div>
    );
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-lilac-50 via-white to-purple-100 font-sans selection:bg-lilac-200">
      
      {/* Header / Navigation */}
      <nav className="fixed top-0 left-0 right-0 bg-white/80 backdrop-blur-lg border-b border-lilac-100 shadow-sm z-50 px-4 py-3">
        <div className="max-w-7xl mx-auto flex items-center justify-between">
          <div className="flex items-center gap-2 cursor-pointer" onClick={() => setView('list')}>
            <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-lilac-500 to-purple-600 flex items-center justify-center text-white font-bold text-xl shadow-lg shadow-lilac-200">
              V
            </div>
            <h1 className="text-xl md:text-2xl font-bold text-lilac-900 tracking-tight hidden sm:block">
              Gestor <span className="text-lilac-500">VIVO_SC</span>
            </h1>
          </div>

          <div className="flex items-center gap-2 md:gap-4">
            <button 
                onClick={loadData}
                disabled={loading}
                className="p-3 rounded-2xl text-lilac-400 hover:bg-lilac-50 transition-all mr-2"
                title="Atualizar Dados"
            >
                <RefreshCw size={20} className={loading ? "animate-spin" : ""} />
            </button>

            <button 
              onClick={() => setView('list')}
              className={`p-3 rounded-2xl transition-all ${view === 'list' ? 'bg-lilac-100 text-lilac-700 font-bold' : 'text-slate-500 hover:bg-slate-50'}`}
              title="Registros"
            >
              <List size={24} />
            </button>

            <button 
              onClick={() => setView('dashboard')}
              className={`p-3 rounded-2xl transition-all ${view === 'dashboard' ? 'bg-lilac-100 text-lilac-700 font-bold' : 'text-slate-500 hover:bg-slate-50'}`}
              title="Dashboard"
            >
              <BarChart3 size={24} />
            </button>

            <button 
              onClick={handleAdminClick}
              className={`p-3 rounded-2xl transition-all ${view === 'admin' ? 'bg-lilac-100 text-lilac-700 font-bold' : 'text-slate-500 hover:bg-slate-50'}`}
              title="Administração"
            >
              <LayoutGrid size={24} />
            </button>
          </div>
        </div>
      </nav>

      {/* Main Content */}
      <main className="pt-24 pb-12 px-4 md:px-6 max-w-7xl mx-auto">
        
        {view === 'list' && (
          <div className="relative">
            <div className="flex justify-end gap-3 mb-6 sticky top-24 z-30">
               <Button onClick={handleExportExcel} size="lg" variant="secondary" icon={<Download size={20} />} className="shadow-xl shadow-lilac-100 border-lilac-200 text-lilac-700 hover:bg-green-50 hover:text-green-700 hover:border-green-200">
                 Excel
               </Button>
               <Button onClick={handleCreateNew} size="lg" icon={<Plus />} className="shadow-2xl shadow-lilac-300/50">
                 Novo Registro
               </Button>
            </div>
            {/* O indicador de loading global foi removido daqui para não esconder a lista, 
                agora é controlado internamente pelo OrderList para bloquear botões */}
            <OrderList 
                orders={orders} 
                config={config}
                onEdit={handleEditOrder} 
                onDelete={handleDeleteOrder}
                isLoading={loading}
            />
          </div>
        )}

        {view === 'dashboard' && (
            <Dashboard orders={orders} config={config} />
        )}

        {view === 'form' && (
          <OrderForm 
            config={config} 
            initialData={editingOrder} 
            onSave={handleSaveOrder} 
            onCancel={() => setView('list')} 
          />
        )}

        {view === 'admin' && (
          <>
            {!isAdminAuthenticated ? (
               <AdminLogin 
                 onLoginSuccess={() => setIsAdminAuthenticated(true)} 
                 onCancel={() => setView('list')} 
               />
            ) : (
              <AdminPanel 
                config={config} 
                onUpdateConfig={handleUpdateConfig} 
              />
            )}
          </>
        )}

      </main>
    </div>
  );
}

const SettingsIcon = ({ size }: { size: number }) => (
    <svg xmlns="http://www.w3.org/2000/svg" width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M12.22 2h-.44a2 2 0 0 0-2 2v.18a2 2 0 0 1-1 1.73l-.43.25a2 2 0 0 1-2 0l-.15-.08a2 2 0 0 0-2.73.73l-.22.38a2 2 0 0 0 .73 2.73l.15.1a2 2 0 0 1 1 1.72v.51a2 2 0 0 1-1 1.74l-.15.09a2 2 0 0 0-.73 2.73l.22.38a2 2 0 0 0 2.73.73l.15-.08a2 2 0 0 1 2 0l.43.25a2 2 0 0 1 1 1.73V20a2 2 0 0 0 2 2h.44a2 2 0 0 0 2-2v-.18a2 2 0 0 1 1-1.73l.43-.25a2 2 0 0 1 2 0l.15.08a2 2 0 0 0 2.73-.73l.22-.39a2 2 0 0 0-.73-2.73l-.15-.08a2 2 0 0 1-1-1.74v-.47a2 2 0 0 1 1-1.74l.15-.09a2 2 0 0 0 .73-2.73l-.22-.38a2 2 0 0 0-2.73-.73l-.15.08a2 2 0 0 1-2 0l-.43-.25a2 2 0 0 1-1-1.73V4a2 2 0 0 0-2-2z"></path><circle cx="12" cy="12" r="3"></circle></svg>
);

export default App;
